#!/usr/bin/env bash
#transfer file
case $# in
    4)
    scp -o StrictHostKeyChecking=no -i "$4" "$3"@"$2" "$1":~/
    ;;
    *)
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    ;;
esac