#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update && sudo apt-get install nginx -y
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
