#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server

sudo apt-get update && sudo apt-get install haproxy
sudo echo "frontend my_front
        bind: *:80
        mode http
        default_backend my_back

backend my_back
        balance roundrobin
        server 2794-web-01 34.138.93.148:80 check
        server 2794-web-02 35.231.107.152:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
