#!/usr/bin/env bash
# Backup for all Mysql databases

# Connect using password as an argument &
# dump all databases into backup.sql file

mysql -uroot -p "$1" --all-databases > backup.sql

# Compress backup.sql into a tar.gz,
# format: day-month-year.tar.gz

tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
