#!/usr/bin/env bash
#Ping the IP 5 times
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed

case $# in
    1)
        ping -c 5 "$@"
        ;;
    *)
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
esac
