#!/usr/bin/env bash
#Displays content of a file -> only:
#username, user id, home directory path for the user

file="/etc/passwd"
while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < $file
