#!/usr/bin/env bash
#Print Holberton School and print Hi if 
#counter equal to 9
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    (( counter++ ))
done
