#!/usr/bin/env bash
#Run nginx as nginx user on port 8080
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo chmod 004 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
